[Interface]
Address = 10.13.13.2
PrivateKey = aKNRlIr9vVSkGsAG7+uwL4iwoIpnP6pEGTDc+qyzikk=
ListenPort = 51820
DNS = 1.1.1.1

[Peer]
PublicKey = fpYjvE71FhaQfWXjx0Wpn0FYOS6HkN4aWve6WBsN0hs=
PresharedKey = Nwusmbk6VnPOtIsJS/Crzf3fag8OE7wFTS386jku+NM=
Endpoint = 217.32.161.236:51820
AllowedIPs = 0.0.0.0/0
