[Interface]
Address = 10.13.13.2
PrivateKey = eNGRiAG6ruDiHmzr6TVr/bl0VBXQc/2uaw/ZmreqX3s=

[Peer]
PublicKey = yEFCOv1XehRXnHIGpYKDWAtJF9IDX9JTzAwOV6PMsVM=
PresharedKey = mYEOPLl5eo2kKRJGMdIf2yrtBG3NUEYvoH9kLKti1QI=
Endpoint = 127.0.0.1:51820
AllowedIPs = 172.30.30.0/24
