[Interface]
MTU = 1200
Address = 10.13.13.2
PrivateKey = gBHjhyNx8ALzCUvIBlsRGhKZNH3xqOL9AQ5ZEjzXeFs=

[Peer]
PublicKey = QlFSOhce9fh+yEfMTekKekQSWK2PVTrsicNTrC9sZHc=
PresharedKey = PuzCCMvDGDc0/t0lXRbaZOFlPl70bceXr3T8FapE1O0=
Endpoint = 127.0.0.1:51820
AllowedIPs = 172.30.30.0/24
