[Interface]
MTU = 1200
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = SF4uyyHbcLeiF6Nbdlu9HzX5SVtmqFlsUJfikwbOS08=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_client1
PublicKey = Pu+AtDDPACqmrAgviOBVWWCkwKwK+xgT2aoY4HwAcDA=
PresharedKey = +8efXU8yc3gY27Z+nUcrXCMVHhUtY8rQwKz3pq00dZU=
AllowedIPs = 10.13.13.2/32
