[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = +PmG7KWIcftGwVM2hP4b79NEdbE2nIS+MeKGFAn5IWo=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_client1
PublicKey = 5AH7f1UMEjjW9ZEK+LFvro+9gcxFZ32RbDanjrWhVRQ=
PresharedKey = PuzCCMvDGDc0/t0lXRbaZOFlPl70bceXr3T8FapE1O0=
AllowedIPs = 10.13.13.2/32

