[Interface]
MTU = 1200
Address = 10.13.13.2
PrivateKey = qIrNPwKiDfi91vwq0Lp8gMVo3XXL2tTO39m7HhTMJEg=

[Peer]
PublicKey = ewUBdmojq/lsomuNzrsutvtikAX5bS3gS+cAOpp9G2o=
PresharedKey = +8efXU8yc3gY27Z+nUcrXCMVHhUtY8rQwKz3pq00dZU=
Endpoint = 127.0.0.1:51820
AllowedIPs = 172.30.30.0/24
