[Interface]
MTU = 1200
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = QF2ikvjsc3FziLAvYN8ThqAGGA1YL65fEP0+qih1AmA=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_client1
PublicKey = Lhcds+vgJUGzcbPOVKgN/dfGW4p17kIYK18pFYXCWHY=
PresharedKey = co9SuXl+gyuJYTShNMiyzoDLxyrh4gpkLPDju4lYh0o=
AllowedIPs = 10.13.13.2/32
