name: vpn-lab-baseline

services:
  target:
    image: nginx:alpine
    container_name: target-server
    networks:
      - external_net

  gateway:
    image: linuxserver/wireguard:latest
    container_name: vpn-gateway
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/London}
      - SERVERPORT=${WG_SERVER_PORT:-51820}
      - PEERS=${WG_PEER_NAME:-client1}
      - PEERDNS=1.1.1.1
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ../services/gateway/wireguard:/config
      - /lib/modules:/lib/modules:ro
    networks:
      - client_net
      - external_net

  client:
    build:
      context: ../services/client
    container_name: client-node
    network_mode: "service:wg-client"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - wg-client

  wg-client:
    build:
      context: ../services/wg-client
    container_name: wg-client
    cap_add:
      - NET_ADMIN
    volumes:
      - ../services/wg-client/wireguard:/config:ro
    networks:
      - client_net
    depends_on:
      - gateway

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata-ids
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ../services/suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ../services/suricata/rules:/var/lib/suricata/rules
      - ../results/suricata-alerts:/var/log/suricata
    command: ["-i", "${BRIDGE_IF:-br-2be230386d09}", "-l", "/var/log/suricata", "-c", "/etc/suricata/suricata.yaml"]

networks:
  client_net:
    driver: bridge
  external_net:
    driver: bridge
