[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = uABwSse6K/BEmroPBrRHppN4irU19IXZjJa3ssECpno=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_client1
PublicKey = DNGpFS46OmZpUtdism4e/clqjC375k4rTeoWxmPULy0=
PresharedKey = Nwusmbk6VnPOtIsJS/Crzf3fag8OE7wFTS386jku+NM=
AllowedIPs = 10.13.13.2/32

