[Interface]
Address = 10.13.13.2/32
PrivateKey = GNu3QSlykIszgU8/vXqx4z6jOUEhIjkuuOnmkPppMmM=
ListenPort = 51821

[Peer]
PublicKey = AbglTr1s7cAlB+DQQ0cDLg/kayg/ytIZ/QE9otsXt0s=
PresharedKey = hCnFkTruZnlUsRJ1sF/y7mRekeqV+tnu9d0lTt+fLRA=
# Connect to udp2raw-client on localhost (which unwraps TCP/443 → UDP/51820)
Endpoint = 127.0.0.1:51820
AllowedIPs = 172.30.30.0/24
PersistentKeepalive = 25
