[Interface]
Address = 10.13.13.2
PrivateKey = aKNRlIr9vVSkGsAG7+uwL4iwoIpnP6pEGTDc+qyzikk=

[Peer]
PublicKey = fpYjvE71FhaQfWXjx0Wpn0FYOS6HkN4aWve6WBsN0hs=
PresharedKey = Nwusmbk6VnPOtIsJS/Crzf3fag8OE7wFTS386jku+NM=
Endpoint = 192.168.10.2:51820
AllowedIPs = 172.30.30.0/24
