[Interface]
MTU = 1200
Address = 10.13.13.2
PrivateKey = oJi1aiRsbEAEfSc17gMU6njULjs4IjcDU3Uw+3bK8nA=

[Peer]
PublicKey = QlOt1DecogPbOqzl8UKJbuaztHbX/N95yfUyNDHBbns=
PresharedKey = co9SuXl+gyuJYTShNMiyzoDLxyrh4gpkLPDju4lYh0o=
Endpoint = 127.0.0.1:51820
AllowedIPs = 172.30.30.0/24
